"""The codoc data model, as shipped in ``model.json``.

``model.json`` is generated by ``build_model.py`` from the upstream docs
(https://github.com/codoc-health/codoc-data-model-docs) and pinned to the
commit recorded in its ``source`` block.
"""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

MODEL_PATH = Path(__file__).with_name("model.json")

# codoc datatype -> the family a source column must belong to.
FAMILIES = {
    "bigint": "integer",
    "integer": "integer",
    "double": "float",
    "varchar": "string",
    "text": "string",
    "timestamptz": "datetime",
    "date": "date",
    "boolean": "boolean",
}


@dataclass(frozen=True)
class Column:
    name: str
    datatype: str
    length: Optional[int]
    required: bool
    primary_key: bool
    foreign_key: Optional[str]
    extension: Optional[str] = None

    @property
    def family(self) -> str:
        return FAMILIES[self.datatype]

    @property
    def declared_type(self) -> str:
        """The type as the upstream docs write it, e.g. ``varchar(120)``."""
        if self.length is None:
            return self.datatype
        return f"{self.datatype}({self.length})"

    @property
    def max_length(self) -> Optional[int]:
        """Character limit to enforce, only for bounded text columns."""
        return self.length if self.datatype == "varchar" else None


@dataclass(frozen=True)
class Table:
    name: str
    domain: Optional[str]
    columns: Tuple[Column, ...]
    extension_columns: Tuple[Column, ...]

    def expected_columns(self, extensions: Iterable[str] = ()) -> List[Column]:
        """Columns the table must carry with the given extensions enabled."""
        enabled = set(extensions)
        return list(self.columns) + [
            column
            for column in self.extension_columns
            if column.extension in enabled
        ]

    def known_columns(self) -> Dict[str, Column]:
        """Every column the model defines, extensions included, by name."""
        return {
            column.name: column
            for column in self.columns + self.extension_columns
        }


@dataclass(frozen=True)
class Model:
    repository: str
    commit: str
    tables: Dict[str, Table]

    @property
    def extensions(self) -> List[str]:
        return sorted(
            {
                column.extension
                for table in self.tables.values()
                for column in table.extension_columns
            }
        )


def _column(raw: dict, extension: Optional[str] = None) -> Column:
    return Column(
        name=raw["name"],
        datatype=raw["datatype"],
        length=raw["length"],
        required=raw["required"],
        primary_key=raw["primary_key"],
        foreign_key=raw["foreign_key"],
        extension=extension,
    )


def load_model(path: Path = MODEL_PATH) -> Model:
    raw = json.loads(path.read_text(encoding="utf-8"))
    tables = {}
    for name, table in raw["tables"].items():
        unknown = {c["datatype"] for c in table["columns"]} - set(FAMILIES)
        if unknown:
            raise ValueError(f"{name}: unsupported datatypes {unknown}")
        tables[name] = Table(
            name=name,
            domain=table.get("domain"),
            columns=tuple(_column(c) for c in table["columns"]),
            extension_columns=tuple(
                _column(c, extension)
                for extension, columns in table.get("extensions", {}).items()
                for c in columns
            ),
        )
    return Model(
        repository=raw["source"]["repository"],
        commit=raw["source"]["commit"],
        tables=tables,
    )
